### ISSUE TITLE
Create templates

### ISSUE THREAD

**Issue by bsmoliak** [ReflectiveEarth/reflective-potential#10]
Offering contributors templates for Pull Requests and Issues will help to make the project's documentation more standard and understandable. GitHub maintains some [documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests) describing the _why_, _how_, and _what_ behind these templates.

## Task list
* [x] Add a Pull Request template in a hidden directory
* [x] Add an Issue template for a Bug report in a hidden directory
* [x] Add an Issue template for a Feature request in a hidden directory
* [x] Add a blank Issue template in a hidden directory
* [x] Add a configuration file for the issue templates
